#!/bin/bash
if [ "$#" -lt 1 ]; then
    echo "Illegal number of parameters"
    echo "Usage: " $0 "<roll number>"
    exit 1
fi

ROLL_NO=$(tr '[:lower:]' '[:upper:]' <<< "$1")

FILES="Readme.pdf src/java/cool/Makefile src/java/cool/*.java src/test_cases/Trivial/*.cl src/test_cases/NonTrivial/*.cl"

FILE_NAME="$ROLL_NO\_codegen.tar.gz"

tar cjvf $FILE_NAME $FILES
